<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bianca Santi">
<meta name="dcterms.date" content="2026-05-08">

<title>Introduction to Mixed Effects Modeling – Bianca’s Quarto blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-250a0ad726c327aed60c1b8aba93cc6c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Bianca’s Quarto blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Introduction to Mixed Effects Modeling</h1>
            <p class="subtitle lead">Statistics Final Project (PSY 504)</p>
                                <div class="quarto-categories">
                <div class="quarto-category">code</div>
                <div class="quarto-category">analysis</div>
                <div class="quarto-category">final project</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Bianca Santi </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 8, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>In this tutorial, you will learn what mixed effects linear models are, what situations they should be used in, and how to use them to analyze data in R.</p>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdist)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlmeU)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="loading-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-data">Loading the data</h2>
<p>For this tutorial we’ll be using a dataset included in the nlmeU package. This data comes from the Study of Structural Improvement (SII) Project, which aimed to assess match achievement scores for first and third graders in randomly selected classrooms at elementary schools across the US <span class="citation" data-cites="hill_effects_2005">(<a href="#ref-hill_effects_2005" role="doc-biblioref">Hill, Rowan, and Ball 2005</a>)</span>. The dataset contains data from 1,190 first graders sampled from 312 classrooms in 107 schools.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data from the nlmeU package</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(SIIdata)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize information for the dataframe </span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(SIIdata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1190 obs. of  12 variables:
 $ sex     : Factor w/ 2 levels "M","F": 2 1 2 1 1 2 1 1 2 1 ...
 $ minority: Factor w/ 2 levels "Mnrt=No","Mnrt=Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ mathkind: int  448 460 511 449 425 450 452 443 422 480 ...
 $ mathgain: int  32 109 56 83 53 65 51 66 88 -7 ...
 $ ses     : num  0.46 -0.27 -0.03 -0.38 -0.03 0.76 -0.03 0.2 0.64 0.13 ...
 $ yearstea: num  1 1 1 2 2 2 2 2 2 2 ...
 $ mathknow: num  NA NA NA -0.11 -0.11 -0.11 -0.11 -0.11 -0.11 -0.11 ...
 $ housepov: num  0.082 0.082 0.082 0.082 0.082 0.082 0.082 0.082 0.082 0.082 ...
 $ mathprep: num  2 2 2 3.25 3.25 3.25 3.25 3.25 3.25 3.25 ...
 $ classid : Factor w/ 312 levels "1","2","3","4",..: 160 160 160 217 217 217 217 217 217 217 ...
 $ schoolid: Factor w/ 107 levels "1","2","3","4",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ childid : Factor w/ 1190 levels "1","2","3","4",..: 1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
</div>
<p>This dataset is structured hierarchically: each student belongs to a classroom, and each classroom belongs to a school. The 12 variables in the dataset are:</p>
<ul>
<li>school-level variables:
<ul>
<li><code>schoolid</code>: ID number for the school (factor)</li>
<li><code>housepov</code>: percentage of households below the poverty line in the school’s neighborhood (numeric)</li>
</ul></li>
<li>classroom-level variables:
<ul>
<li><code>classid</code>: ID number for the classroom (factor)</li>
<li><code>yearstea</code>: teacher’s years of experience for teaching, in first grade (numeric)</li>
<li><code>mathknow</code>: how well the teacher knows the first grade math curriculum, with higher scores indicating more knowledge (numeric)</li>
<li><code>mathprep</code>: how many courses on first grade math knowledge the teacher follows (numeric)</li>
</ul></li>
<li>student-level variables:
<ul>
<li><code>childid</code>: ID number for the student (factor)</li>
<li><code>sex</code>: the student’s sex (factor with labeled levels 1 (M) and 2 (F))</li>
<li><code>minority</code>: whether or not the student has minority status (factor with labeled levels 1 (Mnrt=No) and 2 (Mnrt=Yes))</li>
<li><code>mathkind</code>: the student’s math score in the spring of kindergarten (numeric, integer)</li>
<li><code>mathgain</code>: the student’s grain in math score from the spring of kindergarten to the spring of first grade (numeric, integer)</li>
<li><code>ses</code>: the student’s socioeconomic status (numeric)</li>
</ul></li>
</ul>
<p>Over the course of this tutorial, we’ll be exploring the effect of the school-level, classroom-level, and student-level variables on the students’ gain in math scores between kindergarten and first grade.</p>
</section>
<section id="why-not-use-simple-linear-models" class="level1">
<h1>Why not use simple linear models?</h1>
<p>When looking at this dataset, we could form a simple naive hypothesis: for example, that the scores students get in kindergarten are related to the scores they get in first grade. We can make a scatter plot for these two variables in a smaller subset of the data (just for visualization purposes) to see if this naive hypothesis matches the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>SII_toy_data <span class="ot">&lt;-</span> SIIdata <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">200</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, <span class="fu">aes</span>(<span class="at">x =</span> mathkind, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in math scores based on kindergarten scores"</span>, </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Kindergarten math achievement score"</span>, </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Indeed, that seems to be the case! The linear line of best fit shows a correlation between kindergarten scores and score gain, with students that scored higher in kindergarten having a lower gain from kindergarten to first grade. This makes sense: higher scores leave less room for improvement, while students with initially lower scores have much more potential to improve. However, it could also be possible to have a classroom environment where the teacher is better at supporting already high-achieving students, while lower-achieving students don’t get as much support and therefore improve less.</p>
<p>Is more improvement for initially lower-scoring students a global phenomenon, or is the opposite effect also possible? To begin answering this question, we can try looking at the same plot as above, but this time visualize the different classrooms and add in a trend line for each classroom.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> mathkind, <span class="at">y =</span> mathgain, <span class="at">color =</span> classid)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in math scores based on kindergarten scores"</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Grouping by classroom"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Kindergarten math achievement score"</span>, </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When we group the data this way, the picture that emerges is a bit more complicated: some classrooms still show the overall effect, with lower initial scores being correlated with more score gain. Some classrooms show the effect even more strongly with steeper downwards trend lines. However, some classrooms show the opposite effect: a higher initial score is correlated with more gain. This suggests that the relationship between kindergarten scores and score gain in first grade is not as simple as it may initially seem, and it might depend on some classroom-level variables, such as how effective the teacher is at teaching first grade math.</p>
<p>Another naive hypothesis we might form is that children from higher socioeconomic backgrounds (high SES) might have a higher gain in math scores. Once again, we can explore this hypothesis with a scatter plot in our subset of the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, <span class="fu">aes</span>(<span class="at">x =</span> ses, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in math scores based on kindergarten scores"</span>, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Socioeconomic status"</span>, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If we plot the score gain against SES within the same subset of the data, however, this doesn’t seem to be the case: the linear trend line for this correlation is basically flat. This might be because there is no correlation between SES and math score gain, but it might also be because the correlation between these factors is variable. For example, it could be that some school districts have more resources to support lower-income students and therefore have more flat or even decreasing trend lines, but in other school districts with less resources lower-income students aren’t able to increase their score as much. Once again, we can begin to uncover this variation by plotting the data with different trend lines for each school.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> ses, <span class="at">y =</span> mathgain, <span class="at">color =</span> schoolid)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Change in math scores based on kindergarten scores"</span>, </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Grouping by school"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Socioeconomic status"</span>, </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>While the overall correlation was pretty flat, plotting the trend lines for each school shows a lot more variation: in some schools SES is positively correlated with score increases, in others the correlation is flat, and in one district the correlation is negative, so that higher income students improve their scores less. Once again, grouping the data revealed substantial variation, this time at the level of the school, which suggests that the relationship between SES and math score gain might be influenced by school-level variables.</p>
<p>These examples illustrate a common issue with using simple linear models to explain relationships in complicated, real-world datasets: simple linear models assume each data point is independent, while in the real world data points are often grouped and interdependent. Simple linear models can’t account for the fact that students in the same classroom are probably more similar than students in different classrooms, and classrooms in the same school are probably more similar than classrooms in different schools. They also can’t account for the variation that exists between groups: each grouping variable (classroom and school) can have different means for each variable and different slopes for relationships between variables.</p>
<p>Mixed effects models allow us to deal with this complexity in a dataset: they are made for dealing with data points that are not independent and are instead clustered or nested. Because of that, they can capture more of the meaningful variation in complex datasets like this and produce much more accurate predictions. Using mixed effects models is preferable when dealing with datasets that feature nested designs (such as the SII dataset we’re using here), repeated measures for each participant, longitudinal data, or generally complex designs.</p>
</section>
<section id="manually-building-a-mixed-effects-model" class="level1">
<h1>Manually building a mixed effects model</h1>
<section id="starting-with-a-simple-linear-model" class="level3">
<h3 class="anchored" data-anchor-id="starting-with-a-simple-linear-model">Starting with a simple linear model</h3>
<p>In a simple linear model, a linear correlation is fit to the data and each data point is assumed to be independent, so any variation between groups is assumed to be normally distributed error.</p>
<p>In a subset of the data, we could fit a linear model for the relationship between kindergarten math scores and math score gain. We can use the <code>lm</code> function to fit a simple linear model that predicts math score gain based on kindergarten math scores (<code>mathgain ~ ses</code>); we are assuming that all other variation in the data is random error.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># take a smaller subset (n = 100) for visualization purposes</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>SII_toy_data <span class="ot">&lt;-</span> SII_toy_data <span class="sc">%&gt;%</span> <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>toy_lm_kind <span class="ot">&lt;-</span> <span class="fu">lm</span>(mathgain <span class="sc">~</span> mathkind, <span class="at">data =</span> SII_toy_data)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(toy_lm_kind)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mathgain ~ mathkind, data = SII_toy_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-180.472  -16.397   -0.255   15.386  106.609 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 187.7663    47.8021   3.928 0.000159 ***
mathkind     -0.2703     0.1023  -2.643 0.009569 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 35.73 on 98 degrees of freedom
Multiple R-squared:  0.06654,   Adjusted R-squared:  0.05701 
F-statistic: 6.985 on 1 and 98 DF,  p-value: 0.009569</code></pre>
</div>
</div>
<p>As we expected from the trend line above, the relationship between math score increase and kindergarten math scores is significant and negative: students with higher scores in kindergarten generally improve less by third grade (p &lt; 0.01).</p>
<p>When we plot the model predictions for each of the different classrooms in this subset of the data, we can see how the linear model doesn’t track group-level effects: the slope and intercept (height on the plot) of the trend line is exactly the same for each of the classrooms. This means that the trend lines don’t fit the classroom-level data very well: some of them are too high or too low with respect to the data points, and the slopes don’t match the classroom-level trends well either.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>SII_toy_data<span class="sc">$</span>pred_lm_kind <span class="ot">&lt;-</span> <span class="fu">predict</span>(toy_lm_kind)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> mathkind)) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> mathgain), <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span>.<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>schoolid) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred_lm_kind), <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Linear model fit for each classroom"</span>, </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"mathgain ~ mathkind"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Kindergarten math achievement score"</span>, </span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="adding-random-intercepts" class="level3">
<h3 class="anchored" data-anchor-id="adding-random-intercepts">Adding random intercepts</h3>
<p>One of the way that mixed effects models can account for variation between grouping variables is by adding random intercepts. Instead of assuming one intercept for the line of best fit across all the data, we can allow the intercept to vary between groups, so that each group has its own intercept (but the same slope). This means that the variance in intercepts (or conceptually, in the average math score gain) between different classrooms is no longer modeled as error, but is instead modeled as a distribution of deviations from the overall mean intercept.</p>
<p>To do this in R, we can use the <code>lmer</code> function from the <code>lmerTest</code> package to fit a mixed effects model that still predicts math score gain based on kindergarten math scores (<code>mathgain ~ mathkind</code>), but this time adds in a term for random intercepts for each classroom <code>(1 | classid)</code>. This model has two components:</p>
<ul>
<li>Fixed (or constant) effects - population-level effects that persist across groups. In our case, this is the population-level intercept and slope for the effect of kindergarten math scores.</li>
<li>Random effects - effects that vary for each group and model additional variation as a distribution around the fixed effects. In our case, we are adding in one random effect: random intercepts for each classroom.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>toy_intercept_kind <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> mathkind <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> schoolid), <span class="at">data =</span> SII_toy_data)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(toy_intercept_kind)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ mathkind + (1 | schoolid)
   Data: SII_toy_data

REML criterion at convergence: 990.3

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.9892 -0.5209  0.0190  0.4826  3.3163 

Random effects:
 Groups   Name        Variance Std.Dev.
 schoolid (Intercept)  175.4   13.24   
 Residual             1118.4   33.44   
Number of obs: 100, groups:  schoolid, 10

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 195.1796    50.2853  92.9179   3.881 0.000194 ***
mathkind     -0.2897     0.1076  93.6131  -2.692 0.008415 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
         (Intr)
mathkind -0.994</code></pre>
</div>
</div>
<p>This model still shows a significant negative relationship between math score increase and kindergarten math scores (p = 0.011). However, it is now also modeling variance in intercepts for each classroom, which accounts for ~18% (231 / (231 + 1065)) of the total variance in the data.</p>
<p>When we visualize the predictions from this model for each classroom, we can notice that the predictions for each classroom still have the same slope but now vary in intercept (height) and capture the differences in average math score gains between classrooms a bit better.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>SII_toy_data<span class="sc">$</span>pred_intercept_kind <span class="ot">&lt;-</span> <span class="fu">predict</span>(toy_intercept_kind)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> mathkind)) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> mathgain), <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span>.<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>schoolid) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred_intercept_kind), <span class="at">col =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Random intercepts fit for each classroom"</span>, </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"mathgain ~ mathkind + (1 | classid)"</span>, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Kindergarten math achievement score"</span>, </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="adding-random-slopes" class="level3">
<h3 class="anchored" data-anchor-id="adding-random-slopes">Adding random slopes</h3>
<p>The other random effect that we can account for with a mixed effects model is different slopes for each group. Instead of assuming that the slope of the predicted line must be the same across all groups, we can add in a random slopes term and allow the slope to vary between groups. This means that the variance in slopes (conceptually, the relationship between kindergarten scores and score gains) between different classrooms is no longer modeled as an error, but is instead considered a distribution of deviations from the overall population-level slope.</p>
<p>We can add this change to our previous model, so that now each group has both its own intercept and its own slope. With the <code>lmer</code> package, we can now fit a mixed effects model that predicts math score gain based on kindergarten math scores (<code>mathgain ~ mathkind</code>) and adds in terms for random intercepts for each classroom <code>(1 | classid)</code> and random slopes for the effect of kindergarten math scores by classroom <code>(mathkind | classid)</code>, which are combined into <code>(1 + mathkind | classid)</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>toy_intercept_slopes_kind <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> mathkind <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> mathkind <span class="sc">|</span> schoolid), <span class="at">data =</span> SII_toy_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(toy_intercept_slopes_kind)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ mathkind + (1 + mathkind | schoolid)
   Data: SII_toy_data

REML criterion at convergence: 989.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.9218 -0.5069  0.0124  0.4703  3.3255 

Random effects:
 Groups   Name        Variance  Std.Dev. Corr  
 schoolid (Intercept) 1.109e+03 33.30499       
          mathkind    1.917e-03  0.04379 -1.00 
 Residual             1.112e+03 33.35262       
Number of obs: 100, groups:  schoolid, 10

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 195.8090    50.5916  56.7392    3.87 0.000283 ***
mathkind     -0.2909     0.1069  91.2390   -2.72 0.007817 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
         (Intr)
mathkind -0.994
optimizer (nloptwrap) convergence code: 0 (OK)
boundary (singular) fit: see help('isSingular')</code></pre>
</div>
</div>
<p>Once again, this model shows a significant negative relationship between math score increase and kindergarten math scores (p &lt; 0.01). This model is still modeling variance in intercepts for each classroom, which accounts for ~50% (1109 / (1109 + 1112 + 0.001917)) of the total variance, and is now also modeling variance in slopes for each classrooms, which doesn’t actually account for much of the variance (&lt; 0.0001%). This means that adding random slopes didn’t do too much to improve model fit.</p>
<p>We can still visualize the predictions from this model for each classroom, but because the random slopes didn’t account for a lot of the variance we can’t really see noticeable differences in slopes between each classroom. However, if the addition of random slopes was more impactful, we would be able to see that the predictions for each classroom not only vary in intercept (height) but also in slopes to capture the spread of the data a bit better.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>SII_toy_data<span class="sc">$</span>pred_intercept_slopes_kind <span class="ot">&lt;-</span> <span class="fu">predict</span>(toy_intercept_slopes_kind)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SII_toy_data, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> mathkind)) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> mathgain), <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span>.<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>schoolid) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred_intercept_slopes_kind), <span class="at">col =</span> <span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Random intercepts + slopes fit for each classroom"</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"mathgain ~ mathkind + (1 + mathkind | classid)"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Kindergarten math achievement score"</span>, </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="mixed-effects-modeling-in-r" class="level1">
<h1>Mixed effects modeling in R</h1>
<p>Now that we know the added features of mixed effects models, random effects (random intercepts and random slopes), we can go over how to implement mixed effects modeling in R. In this tutorial, we’ll be using the <code>lmerTest</code> package to implement all mixed effects models. The general workflow for modeling data with mixed effects models is:</p>
<ol type="1">
<li>Exploring relationships between variables</li>
<li>Implementing model(s)</li>
<li>Model comparison</li>
<li>Interpreting model outputs</li>
</ol>
<p>Let’s go through these steps one by one.</p>
<section id="exploring-relationships-between-variables" class="level2">
<h2 class="anchored" data-anchor-id="exploring-relationships-between-variables">Exploring relationships between variables</h2>
<p>Visualizing data is always a helpful first step before doing statistical modeling. In our case, without any a priori hypotheses or analysis plan, visualizing the data and relationships between variables also helps us determine what variables should be included in our statistical models.</p>
<p>One helpful visualization (that we’ve already used above) during data exploration is a scatterplot, which we can use to understand the relationships between continuous variables. Since we’re interested in modeling the gain in math scores between kindergarten and first grade, we can create scatterplots with the <code>mathgain</code> variable on the y axis and other continuous variables on the x axis. Let’s start with kindergarten math scores (<code>mathkind</code>), this time looking at the full sample instead of a subset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> mathkind, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Kindergarten math achievement score"</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this, we can see that the full sample has a fairly even spread in both math gain scores and in kindergarten scores (with the exception of some very low potential outlier values for kindergarten scores). The two variables still seem to be negatively correlated in the full sample, which means kindergarten scores are likely a useful variable to include in our models.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> ses, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Socioeconomic status"</span>, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also look at SES. In the full sample, there still doesn’t seem to be a strong relationship between SES and score gain.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> yearstea, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Teacher's years of teaching experience"</span>, </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> mathknow, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Teacher's math knowledge"</span>, </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> mathprep, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Teacher's math prep courses"</span>, </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When we look at classroom-level variables, we don’t observe any noticeable correlations between gain in math scores and the teacher’s years of teaching experience, level of math knowledge, or amount of math courses they follow. Based on this, these variables might be excluded from our statistical models for the sake of simplicity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> housepov, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Percentage of houses below poverty level in school neighborhood"</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The final variable we can explore with a scatterplot is the percentage of houses below poverty level in school neighborhood (<code>housepov</code>), which is a school-level variable.</p>
<p>Some of the other predictor variables are not continuous but rather categorical factors and can’t be visualized with scatterplots. For these, we can visualize their relationship with <code>mathgain</code> using plots that show the data distribution for each category, such as violin plots.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Student's sex"</span>, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(SIIdata, <span class="fu">aes</span>(<span class="at">x =</span> minority, <span class="at">y =</span> mathgain)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Student's minority status"</span>, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gain in math scores from kindergarten to first grade"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The two categorical student-level variables, sex and minority status seem to correlate with score gain a bit, since the distributions look slightly wider and have lower means for the female and minority students.</p>
<p>Now that we’ve visualized some of the variance in our data, we can move on to building mixed effects models to model our data.</p>
</section>
<section id="implementing-different-models" class="level2">
<h2 class="anchored" data-anchor-id="implementing-different-models">Implementing different models</h2>
<p>In order to implement a mixed effects model, we need to decide which fixed and random effects to include in our model structure. The fixed effects represent individual predictors, while random effects reflect effects at the group (classroom or school) level.</p>
<p>In our case, we can build a model that predicts the gain in math scores from all student-level predictors (sex, minority status, kindergarten math scores, and SES), the school-level predictor of percentage of households under the poverty level, and one classroom-level predictor that we think might make an impact: years of teaching experience for the classroom teacher. If we assume each of these predictors acts independently, the fixed effects for our model are <code>sex + minority + mathkind + ses + housepov + yearstea</code>.</p>
<p>We can also add in random intercepts for both of the grouping levels we have in our dataset, classrooms and schools, since we expect each to have different baseline levels of gain in math scores. That means that the random effects structure for our first model is <code>(1 | classid) + (1 | schoolid)</code>.</p>
<p>Altogether, this first mixed effects model predicts gain in math scores from the combination of fixed and random effects: <code>mathgain ~ sex + minority + mathkind + ses + housepov + yearstea + (1 | classid) + (1 | schoolid)</code>. We can call it like so using the <code>lmer function</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">+</span> ses <span class="sc">+</span> housepov <span class="sc">+</span> yearstea </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> schoolid), </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can then use the <code>summary()</code> function to see the model output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ sex + minority + mathkind + ses + housepov + yearstea +  
    (1 | classid) + (1 | schoolid)
   Data: SIIdata

REML criterion at convergence: 11380.4

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-5.7859 -0.6126 -0.0295  0.5554  4.2757 

Random effects:
 Groups   Name        Variance Std.Dev.
 classid  (Intercept)  82.23    9.068  
 schoolid (Intercept)  77.31    8.793  
 Residual             734.71   27.106  
Number of obs: 1190, groups:  classid, 312; schoolid, 107

Fixed effects:
                   Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)       284.19767   11.16291 1138.35537  25.459  &lt; 2e-16 ***
sexF               -1.22060    1.65820 1125.34746  -0.736  0.46182    
minorityMnrt=Yes   -7.72157    2.38627  643.38184  -3.236  0.00128 ** 
mathkind           -0.47070    0.02229 1172.24771 -21.118  &lt; 2e-16 ***
ses                 5.23075    1.24542 1170.24409   4.200 2.87e-05 ***
housepov          -10.95369    9.98022  120.72050  -1.098  0.27459    
yearstea            0.05390    0.11236  250.83188   0.480  0.63183    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) sexF   mnrM=Y mthknd ses    houspv
sexF        -0.045                                   
mnrtyMnrt=Y -0.266 -0.015                            
mathkind    -0.959 -0.031  0.154                     
ses          0.124  0.018  0.144 -0.165              
housepov    -0.185 -0.007 -0.180  0.036  0.077       
yearstea    -0.158  0.018  0.032  0.012 -0.013  0.097</code></pre>
</div>
</div>
<p>From this, we can see that the random effects we added account for some amount of the variance, and that we have significant effects of minority status, math scores from kindergarten, and socioeconomic status on the gain in math scores.</p>
<p>We could complicate this model a bit if we have reason to believe that the slopes for some effects could also vary by group. For instance, we might think that the relationship between kindergarten scores and score gain might depend on classroom-level effects, such as teacher characteristics. We could also think that the relationship between SES and math gain could vary between schools. To add these hypotheses to our model, we need to add random slopes for these predictors, which means that our full random effects structure is <code>(1 + mathkind | classid) + (1 + ses | schoolid)</code>. We can implement and summarize this second model using the following syntax:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">+</span> yearstea <span class="sc">+</span> ses <span class="sc">+</span> housepov  </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> mathkind <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> ses<span class="sc">|</span> schoolid), </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ sex + minority + mathkind + yearstea + ses + housepov +  
    (1 + mathkind | classid) + (1 + ses | schoolid)
   Data: SIIdata

REML criterion at convergence: 11466.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-5.6821 -0.6148 -0.0167  0.5646  4.4779 

Random effects:
 Groups   Name        Variance  Std.Dev. Corr  
 classid  (Intercept) 8.219e+02 28.66935       
          mathkind    3.784e-03  0.06151 -0.95 
 schoolid (Intercept) 8.206e+02 28.64644       
          ses         7.549e+01  8.68838 0.23  
 Residual             6.507e+02 25.50977       
Number of obs: 1190, groups:  classid, 312; schoolid, 107

Fixed effects:
                   Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)       290.62974   12.28992  545.79504  23.648  &lt; 2e-16 ***
sexF               -1.37323    1.61614 1174.05385  -0.850  0.39567    
minorityMnrt=Yes   -8.39492    2.69508  920.40207  -3.115  0.00190 ** 
mathkind           -0.48242    0.02289  838.89111 -21.078  &lt; 2e-16 ***
yearstea            0.01731    0.12628  207.45127   0.137  0.89113    
ses                 5.34095    1.57177   65.75880   3.398  0.00116 ** 
housepov          -13.47967   21.27237  113.63345  -0.634  0.52757    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) sexF   mnrM=Y mthknd yearst ses   
sexF        -0.045                                   
mnrtyMnrt=Y -0.228  0.001                            
mathkind    -0.888 -0.025  0.114                     
yearstea    -0.158  0.023  0.008  0.012              
ses          0.126  0.005  0.073 -0.122 -0.012       
housepov    -0.339 -0.008 -0.095  0.015  0.054  0.018
optimizer (nloptwrap) convergence code: 0 (OK)
unable to evaluate scaled gradient
Model failed to converge: degenerate  Hessian with 2 negative eigenvalues
  See ?lme4::convergence and ?lme4::troubleshooting.</code></pre>
</div>
</div>
<p>However, here we run into one of our first issues with mixed effects models: they can fail to converge if the random effects structure is too complicated. To fix this issue, we can remove one of the random slopes we added in to make the model simpler. In order to make this decision, we remove the random slope that had the smallest effect on the residuals, which in this case is the random slope for kindergarten scores by classroom (<code>mathkind</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">+</span> yearstea <span class="sc">+</span> ses <span class="sc">+</span> housepov  </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> ses<span class="sc">|</span> schoolid), </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ sex + minority + mathkind + yearstea + ses + housepov +  
    (1 | classid) + (1 + ses | schoolid)
   Data: SIIdata

REML criterion at convergence: 11379.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-5.8481 -0.6103 -0.0224  0.5628  4.2746 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 classid  (Intercept)  80.730   8.985        
 schoolid (Intercept)  82.337   9.074        
          ses           7.194   2.682   0.72 
 Residual             731.129  27.039        
Number of obs: 1190, groups:  classid, 312; schoolid, 107

Fixed effects:
                   Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)       284.05953   11.14025 1132.45564  25.498  &lt; 2e-16 ***
sexF               -1.19312    1.65454 1116.01940  -0.721 0.470986    
minorityMnrt=Yes   -7.32591    2.41303  605.68658  -3.036 0.002501 ** 
mathkind           -0.47186    0.02224 1162.45333 -21.214  &lt; 2e-16 ***
yearstea            0.06054    0.11216  250.62232   0.540 0.589812    
ses                 5.19026    1.29153   71.75479   4.019 0.000143 ***
housepov           -9.30493    9.94049  121.70825  -0.936 0.351094    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) sexF   mnrM=Y mthknd yearst ses   
sexF        -0.044                                   
mnrtyMnrt=Y -0.264 -0.016                            
mathkind    -0.958 -0.031  0.150                     
yearstea    -0.158  0.019  0.026  0.013              
ses          0.135  0.019  0.121 -0.156 -0.018       
housepov    -0.185 -0.011 -0.183  0.035  0.102  0.064</code></pre>
</div>
</div>
<p>This model with both random intercepts and random slopes converges, and once again shows a reduction in residual variance through the random effects and significant main effects of minority status, kindergarten math scores, and SES.</p>
<p>But what if we don’t think that each of the fixed effects predictors has an independent effect? For instance, we might think that the relationship between kingergarten scores and gain in math scores depends on the years of teaching experience that the teacher has, or that the effect of SES on score gain is moderated by the poverty level in the notebook. In order to implement this, we can add interactions to our fixed effects: an interaction between kindergarten scores and years of teaching experience, <code>mathkind * yearstea</code>, and an interaction between SES and neighborhood poverty levels, <code>ses * housepov</code>. We don’t need to specify the fixed effects for each of these variables separately, since the syntax for interaction effects also allows us to calculate the independent effects. With this addition, our third model can be called like this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">*</span> yearstea <span class="sc">+</span> ses <span class="sc">*</span> housepov  </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> ses <span class="sc">|</span> schoolid), </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ sex + minority + mathkind * yearstea + ses * housepov +  
    (1 | classid) + (1 + ses | schoolid)
   Data: SIIdata

REML criterion at convergence: 11381.8

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-5.8720 -0.5999 -0.0206  0.5658  4.2650 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 classid  (Intercept)  81.037   9.002        
 schoolid (Intercept)  80.601   8.978        
          ses           4.664   2.160   0.95 
 Residual             733.219  27.078        
Number of obs: 1190, groups:  classid, 312; schoolid, 107

Fixed effects:
                    Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)        2.806e+02  1.723e+01  1.161e+03  16.286  &lt; 2e-16 ***
sexF              -1.245e+00  1.657e+00  1.114e+03  -0.751  0.45257    
minorityMnrt=Yes  -7.229e+00  2.411e+00  6.022e+02  -2.998  0.00283 ** 
mathkind          -4.640e-01  3.566e-02  1.165e+03 -13.012  &lt; 2e-16 ***
yearstea           3.563e-01  1.016e+00  1.138e+03   0.350  0.72603    
ses                7.122e+00  2.076e+00  6.309e+01   3.430  0.00107 ** 
housepov          -1.164e+01  1.016e+01  1.173e+02  -1.146  0.25427    
mathkind:yearstea -6.310e-04  2.164e-03  1.140e+03  -0.292  0.77067    
ses:housepov      -1.110e+01  9.387e+00  1.010e+02  -1.183  0.23966    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) sexF   mnrM=Y mthknd yearst ses    houspv mthkn:
sexF        -0.044                                                 
mnrtyMnrt=Y -0.176 -0.017                                          
mathkind    -0.983 -0.004  0.099                                   
yearstea    -0.769  0.021  0.010  0.778                            
ses          0.085 -0.016  0.085 -0.080 -0.008                     
housepov    -0.165 -0.002 -0.181  0.068  0.065 -0.139              
mthknd:yrst  0.762 -0.019 -0.007 -0.781 -0.994  0.007 -0.055       
ses:housepv -0.035  0.035 -0.012  0.021  0.004 -0.788  0.226 -0.005
fit warnings:
Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
</div>
<p>Once again, this model shows some of the residual variance being accounted for by the random effects and significant main effects of minority status, kindergarten math scores, and SES. Neither of the interactions we added, however, were significant.</p>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model comparison</h2>
<p>Now that we know how to implement mixed effects models, we’re left with the very important question of how to choose which model fits the data the best. As you’ve seen above, we can create several different models to predict one outcome with the same set of predictors in a complex dataset like this one. How do we know which one to use?</p>
<p>One way to resolve this issue is to specify the model ahead of time, before running the analysis, based on your hypotheses (for example, in a preregistration). However, even prespecified models might fail to converge, or you might need to justify using a more complex or simpler model than a different option you might have chosen.</p>
<p>To help in our decision-making, we can use the <code>test_likelihoodratio</code> function from the <code>easystats</code> package, which performs a likelihood ratio test to test which model is a better (more likely) explanation for the data. Crucially, however, this test only works on <em>nested</em> models, which means that all the predictors for one model (the smaller one) should be present in the bigger model.</p>
<p>Let’s use this test to compare two of the models we created earlier: one with just random intercepts by classroom and school (<code>model1</code>) and one with an added random slope for SES by school (<code>model 2</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_likelihoodratio</span>(model1, model2, <span class="at">estimator =</span> <span class="st">"REML"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Some of the nested models seem to be identical and probably only vary in
  their random effects.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Likelihood-Ratio-Test (LRT) for Model Comparison (REML-estimator)

Name   |           Model | df | df_diff | Chi2 |     p
------------------------------------------------------
model1 | lmerModLmerTest | 10 |         |      |      
model2 | lmerModLmerTest | 12 |       2 | 1.23 | 0.540</code></pre>
</div>
</div>
<p>Here, we are using the REML estimator, since the models we are comparing only differ in random effects structure but have identical fixed effects structure. The likelihood ratio test indicates that the addition of random slopes by school for SES did not significantly improve model fit (p = 0.540). That means we can drop the random slope and just use the model with the random intercepts.</p>
<p>We can also compare our <code>model1</code> to slightly more complex models that keep the same random effects structure but include interactions for in the fixed effects.</p>
<p>Let’s create a <code>model4</code> with an interaction between <code>mathkind</code> and <code>yearstea</code>, a <code>model5</code> with an interaction between <code>ses</code> and <code>housepov</code>, and a <code>model6</code> with both interaction terms.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">*</span> yearstea <span class="sc">+</span> ses <span class="sc">+</span> housepov  </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> schoolid), </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">+</span> yearstea <span class="sc">+</span> ses <span class="sc">*</span> housepov  </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> schoolid), </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mathgain <span class="sc">~</span> sex <span class="sc">+</span> minority <span class="sc">+</span> mathkind <span class="sc">*</span> yearstea <span class="sc">+</span> ses <span class="sc">*</span> housepov  </span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>               <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> classid) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> schoolid), </span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> SIIdata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can now compare all of these models to model1 using the likelihood ratio test, this time with the ML estimator since we are comparing models with the same random effects but different fixed effects.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_likelihoodratio</span>(model1, model4, <span class="at">estimator =</span> <span class="st">"ML"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)

Name   |           Model | df | df_diff | Chi2 |     p
------------------------------------------------------
model1 | lmerModLmerTest | 10 |         |      |      
model4 | lmerModLmerTest | 11 |       1 | 0.10 | 0.748</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_likelihoodratio</span>(model1, model5, <span class="at">estimator =</span> <span class="st">"ML"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)

Name   |           Model | df | df_diff | Chi2 |     p
------------------------------------------------------
model1 | lmerModLmerTest | 10 |         |      |      
model5 | lmerModLmerTest | 11 |       1 | 1.35 | 0.246</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_likelihoodratio</span>(model1, model6, <span class="at">estimator =</span> <span class="st">"ML"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)

Name   |           Model | df | df_diff | Chi2 |     p
------------------------------------------------------
model1 | lmerModLmerTest | 10 |         |      |      
model6 | lmerModLmerTest | 12 |       2 | 1.45 | 0.485</code></pre>
</div>
</div>
<p>Through this, we can see that none of the added interaction effects served to significantly improve our model, so <code>model1</code>, out of all the models we explored, seems to provide the best fit to our data.</p>
</section>
<section id="interpreting-model-outputs" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-model-outputs">Interpreting model outputs</h2>
<p>Now that we have our best-fitting model, how do we interpret its outputs? Let’s take a look at the model summary again:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathgain ~ sex + minority + mathkind + ses + housepov + yearstea +  
    (1 | classid) + (1 | schoolid)
   Data: SIIdata

REML criterion at convergence: 11380.4

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-5.7859 -0.6126 -0.0295  0.5554  4.2757 

Random effects:
 Groups   Name        Variance Std.Dev.
 classid  (Intercept)  82.23    9.068  
 schoolid (Intercept)  77.31    8.793  
 Residual             734.71   27.106  
Number of obs: 1190, groups:  classid, 312; schoolid, 107

Fixed effects:
                   Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)       284.19767   11.16291 1138.35537  25.459  &lt; 2e-16 ***
sexF               -1.22060    1.65820 1125.34746  -0.736  0.46182    
minorityMnrt=Yes   -7.72157    2.38627  643.38184  -3.236  0.00128 ** 
mathkind           -0.47070    0.02229 1172.24771 -21.118  &lt; 2e-16 ***
ses                 5.23075    1.24542 1170.24409   4.200 2.87e-05 ***
housepov          -10.95369    9.98022  120.72050  -1.098  0.27459    
yearstea            0.05390    0.11236  250.83188   0.480  0.63183    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) sexF   mnrM=Y mthknd ses    houspv
sexF        -0.045                                   
mnrtyMnrt=Y -0.266 -0.015                            
mathkind    -0.959 -0.031  0.154                     
ses          0.124  0.018  0.144 -0.165              
housepov    -0.185 -0.007 -0.180  0.036  0.077       
yearstea    -0.158  0.018  0.032  0.012 -0.013  0.097</code></pre>
</div>
</div>
<p>The random effects portion of the model output shows us how much variance each random effect accounts for. Here, we can see that both of our group random intercepts account for a good amount of the variance in the model, but there is still substantial residual variance.</p>
<p>The fixed effects portion of the model output shows the estimate, standard error, and p values for each of our fixed effects coefficients. For a continuous predictor, like kindergarten math scores, we can interpret the estimate as showing us the estimated change in our outcome (gain in math scores) based on a one-unit increase in the predictor: in this case, scoring one more point in kindergarten predicts -0.47 less points of gain by first grade. For a categorical predictor, like minority status, the estimate shows the estimated change in the outcome for a certain predictor category relative to the reference category. For minority status, the reference level is “no”, so we can interpret the estimate as showing that minority students on average have 7.72 less points of math score gains compared to non-minority students. By looking at the p values, we can understand which of our predictors were significant: in this case, minority status, kindergarten scores, and SES all significantly predict the gain in scores between kindergarten and first grade.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this tutorial, we learned what linear mixed effects models are, when and why we need to use them, how random effects work, and how to implement statistical analyses with linear mixed effects models in R, using the SII dataset of student math scores as an example.</p>
<p>Linear mixed effects models are a powerful statistical tool, especially for complex datasets with nesting structure or repeated measurements, and learning how to implement them is helpful for performing analyses in complex datasets. While powerful, these models still operate within the frequentist framework and have several of the limitations associated with linear regression, so depending on your research questions and design, alternative methods like hierarchical Bayesian models might be more appropriate.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-hill_effects_2005" class="csl-entry" role="listitem">
Hill, Heather C., Brian Rowan, and Deborah Loewenberg Ball. 2005. <span>“Effects of <span>Teachers</span>’ <span>Mathematical</span> <span>Knowledge</span> for <span>Teaching</span> on <span>Student</span> <span>Achievement</span>.”</span> <em>American Educational Research Journal</em> 42 (2): 371–406. <a href="https://doi.org/10.3102/00028312042002371">https://doi.org/10.3102/00028312042002371</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/your-website-url\.example\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>